[build]
  publish = "."
  command = "echo 'No build command needed'"

[build.environment]
  NODE_VERSION = "20.6.0"

# Form settings
[context.production.forms]
  success_page = "/success.html"

# Redirect rules for single page application
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[[redirects]]
  from = "/landing"
  to = "/landing.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/feedback"
  to = "/feedback.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

# Default page redirect
[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

# Catch-all redirect for 404s
[[redirects]]
  from = "/*"
  to = "/landing.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"